# _config.yml
title: Your Site Title
description: Your site description
baseurl: "" # Leave empty if you're deploying to the root
url: "http://127.0.0.1:4000" # Only for local testing
permalink: /:categories/:title/
collections:
  pages:
    output: true
