# _config.yml
title: Mariopuff
description: descroption
baseurl: "" # Leave empty if you're deploying to the root
url: "http://127.0.0.1:5500" # Only for local testing
permalink: /:categories/:title/
collections:
  pages:
    output: true
  projects:
    output: true
    permalink: /projects/:name/

markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
  - jekyll-seo-tag

liquid:
  error_mode: warn

# Force rebuild